-- AlterTable
ALTER TABLE `article` ADD COLUMN `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `comment` ADD COLUMN `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
